// 職責：在無套件環境驗證 v5.9.3 純函式、人工／AI 流程、框選、單位與結果契約。
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { calculateTotalLengthCm, convertLengthToCentimeters, formatLengthCm } from '../src/lib/domain/lengthCalculator.js';
import { answerSelectionQuestion, canSubmitAiQuestion } from '../src/lib/domain/aiAssistant.js';
import { createActiveSelection, isSelectionReady } from '../src/lib/domain/selection.js';
import { currentFlowNodes, futureExteriorSegments, futureFlowSteps, shaftMatrixItems, standardShaftLayers } from '../src/lib/content/siteContent.js';
import { partitionShaftsByLayer } from '../src/lib/domain/layerFilter.js';

assert.ok(Math.abs(convertLengthToCentimeters(16.6, 'm') - 1660) < 1e-9);
assert.equal(convertLengthToCentimeters(1660, 'cm'), 1660);
assert.equal(formatLengthCm(384.25), '384.25 cm');
const selectionData = futureFlowSteps[6].selection;
assert.equal(futureExteriorSegments.length, 16);
assert.equal(futureExteriorSegments.reduce((sum, item) => sum + item.lengthCm, 0), 1000);
assert.equal(selectionData.segmentLengths.length, 22);
assert.equal(calculateTotalLengthCm(selectionData.segmentLengths, 'm'), 1600);
assert.equal(selectionData.lengthObjectIds.length, 22);
assert.equal(selectionData.quantityObjectIds.length, 30);
assert.equal(selectionData.objectIds.length, 52);
assert.equal(selectionData.ignoredObjectIds.length, 2);
assert.deepEqual(selectionData.quantityResults[0], { id: 'triangle-brace', label: '外部三角補強', count: 30, unit: '個', layer: 'AI-BRACE' });
const selection = createActiveSelection(selectionData);
assert.equal(isSelectionReady(selection), true);
assert.equal(canSubmitAiQuestion('總長？', selection), true);
assert.match(answerSelectionQuestion('補強數量？', selection).message, /外部三角補強 30 個/);
assert.equal(currentFlowNodes.length, 9);
assert.equal(futureFlowSteps.length, 12);
assert.equal(currentFlowNodes.some((step) => step.selection), false);
assert.ok(currentFlowNodes.some((step) => step.animType === 'manual-inspect'));
assert.ok(currentFlowNodes.some((step) => step.animType === 'manual-label-slow'));
assert.equal(futureFlowSteps[1].animType, 'standard-layers');
assert.equal(futureFlowSteps.filter((step) => step.selection).length, 3);
for (const step of [...currentFlowNodes, ...futureFlowSteps]) {
  for (const highlight of step.highlights ?? []) assert.ok(`${step.label} ${step.desc}`.includes(highlight.text));
}
const partition = partitionShaftsByLayer(shaftMatrixItems, standardShaftLayers);
assert.equal(partition.accepted.length, 6);
assert.equal(partition.ignored.length, 2);
const root = process.cwd();
const tokens = readFileSync(resolve(root, 'src/lib/tokens.css'), 'utf-8').toLowerCase();
const chart = readFileSync(resolve(root, 'src/lib/charts/cadSimulator.js'), 'utf-8');
const processSource = readFileSync(resolve(root, 'src/lib/components/CadProcess.svelte'), 'utf-8');
const panel = readFileSync(resolve(root, 'src/lib/components/CadDockedPanel.svelte'), 'utf-8');
const assistant = readFileSync(resolve(root, 'src/lib/components/CadAiAssistant.svelte'), 'utf-8');
const summary = readFileSync(resolve(root, 'src/lib/components/Act06Summary.svelte'), 'utf-8');
const nav = readFileSync(resolve(root, 'src/lib/components/Nav.svelte'), 'utf-8');
const svelteConfig = readFileSync(resolve(root, 'svelte.config.js'), 'utf-8');
const pagesWorkflow = readFileSync(resolve(root, '.github/workflows/deploy-pages.yml'), 'utf-8');
['--cad-canvas-background: #e7e8e5', '--cad-playback-rate: 0.5', '--keyword-ai:', '--keyword-standard:', '--keyword-manual:'].forEach((token) => assert.ok(tokens.includes(token)));
['drawHorizontalDimension', 'offsetClosedPolygon', 'drawBraceElement', 'drawManualInspectScene', 'drawManualLabelScene', 'drawStandardLayerScene', 'drawCalculationScene', 'drawResultThreeScene', 'drawAiQueryScene', 'drawExternalIndependentSegments', 'drawTriangleBraces', 'drawOffsetDimension'].forEach((phrase) => assert.ok(chart.includes(phrase)));
assert.ok(processSource.includes('40fr'));
assert.ok(processSource.includes('60fr'));
assert.ok(panel.includes('外部三角補強'));
assert.ok(panel.includes('補強編號'));
assert.ok(tokens.includes('--cad-layer-brace: #ffffff'));
assert.ok(chart.includes("data-location','exterior-perimeter"));
assert.ok(chart.includes("data-brace-geometry','rectangle"));
assert.ok(chart.includes("mode === 'future' ? baseRate * 1.25 : baseRate"));
assert.ok(!chart.includes('人工加總：外部'));
assert.ok(!chart.includes('外部：100＋80＋30＋40＋60＝310.00 cm｜深井')); 
assert.ok(chart.includes("data-dimension-orientation', 'horizontal"));
assert.ok(assistant.includes('typeDemoQuestion'));
assert.ok(assistant.includes('rows="4"'));

assert.ok(processSource.includes('keyword-emphasis'));
assert.ok(futureFlowSteps[3].desc.includes('外部施工線與深井仍由繪圖人員依工程判斷逐段繪製'));
assert.ok(futureFlowSteps[3].desc.includes('AI 不代替繪圖'));
assert.ok(futureFlowSteps[3].desc.includes('自動讀取物件長度並帶入尺寸標註'));
assert.ok(summary.includes('ACT 06 / PROJECT SUMMARY'));
assert.ok(summary.includes('規則化、標準化與系統化'));
assert.ok(summary.includes('把繪圖人員的工程經驗，轉成公司可以保存、團隊可以沿用、程式可以執行、AI 可以使用的標準作業系統。'));
assert.ok(!summary.includes('NEXT STEP'));
assert.ok(!summary.includes('重新檢視現況流程'));
assert.ok(nav.includes("'專案總結'"));
assert.ok(svelteConfig.includes("process.env.GITHUB_REPOSITORY?.split('/')[1]"));
assert.ok(svelteConfig.includes('base: githubPagesBase'));
assert.ok(pagesWorkflow.includes('actions/configure-pages@v5'));
assert.ok(pagesWorkflow.includes('actions/upload-pages-artifact@v4'));
assert.ok(pagesWorkflow.includes('actions/deploy-pages@v4'));
assert.ok(pagesWorkflow.includes('path: build'));
console.log('離線 v5.9.4 人工逐段繪製、AI 完成後帶入尺寸、專案總結與既有流程契約驗證通過。');
